name:                cah-server
version:             0.1.0.0
github:              "knarka/cah"
author:              "knarka"
copyright:           "2022 knarka"

extra-source-files:
- README.md

dependencies:
- base
- scotty
- uuid
- containers
- stm
- random
- mtl
- monadrandom
#- aeson
#- text

default-extensions:
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - OverloadedStrings

executables:
  cah-server-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
